# Build environment for harden-sles15
# Uses bci-go — open SUSE Go Container Image (free, no SLES license required)
# Cross-compiles to Linux/amd64 statically linked binary

FROM registry.suse.com/bci/bci-go:15.5 AS builder
